name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: seecret
          POSTGRES_DB: simple_bank
        ports:
          - 1234:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval="10s"
          --health-timeout="5s"
          --health-retries="5"

    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install golang migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.tar.gz -o migrate.tar.gz
        tar -xvzf migrate.tar.gz
        sudo mv migrate /usr/bin/migrate
        which migrate

    - name: Run migrations
      run: |
        migrate -path db/migrations -database "postgres://root:seecret@localhost:1234/simple_bank?sslmode=disable" up

    - name: Test
      run: |
        export DB_URL="postgres://root:seecret@localhost:1234/simple_bank?sslmode=disable"
        go test -v ./...